language: node_js
node_js:
- 6.9.5
notifications:
  email: false
  webhooks: https://ambrosio-tele.herokuapp.com/sacarinobot/travisci/133188453
  on_success: always
  on_failure: always
  on_start: always
before_script:
- npm install -g grunt-cli
deploy:
  api_key:
    secure: OZMP/rWhxQdXoG33ISAqSID8F/BQ9LOZOyG1QqIJG9FzKSZ+xfsufSWsmSo8Vv44QYsJY8k2+HXdGztOmTv9L0XB/nIg2nDhZ7ggUqIRAqpcFdSIeDIGs3iW/Wr5R7SS9sCALhnpSZtvC9Qk8eixkUjSYZmlY7tGAH7N2gVpTbQbU5dvs/srbDHkcTfXJH9HCHwQKG/ZOk7pOej3LozVmkWB5S6Lt0SMvel5gpXW3GQx1aDKSK++4UfzsHQgx7v1ff6ez9hQPHZgdlVvCFiZB44LBuskiPGpISFt8LKNqWvz/FVfugqKbrL5a1r6max4RkaOIxU32SdiaVfFRo7mRbX5qOFcXcMKDFw4NlMN8CGWKggR6vBWGqnbuhusYdW0Nf7WOApToZ0xDHlRZ7Jq4hGBJkp8sgDR+G90KUghL9m0pcVv0fswQvWkVz/M8NwDzgO1zU8+RYRHcDA8K5pEsrNZERGQNPJZ6+Ax+00BTQLmvhIb0upMc26Rycq0KwMVvDvKOUk2tp41xPRWoaiPjQrwP7WeNUDM9P1tXrK9Jz220ehgnnbdiFwzYSwVJGILBpQ4vOaT5C/Paztjgv5llJRjIBQG577bOddjHHkUR7FM8Qyw3tzNWdJG+KgzxDyQHs/NnOK2gdcjIWnvWHry6qTA/hlSiyMB9YR+SGuPbw0=
  email:
    secure: DfZo6JMtF2W8EvlRpaK7/upN+08fI3OTZs8LO0qK/fT27o6ad2rlAF7HYLLSevVqZSSKB/TfN6NVHhfoJNWfiOw1ZCuhzKwgAgrvx6d6wtwBbxYgcglpoDg6er1LzBFb2f07mxrVmxrbtiLUfXpz6pJf4iFIJsyYsHZHVQk+cWAKz4UkPb2MltpKKsbwfcENL4HJY5GSb0GBl873ue40U9uHBmO2A8aw5UACoXiqPaKjTaQhVoShl6oeah0prkIqKKNbQjsILmUTmqV1jRjKcr3ZA8NAKGayccCJcnJ43Cy83JVHW6L8SbYUWgdxQOsQb0mwe5UBIyxmBcymwoMyyHbaHKIU2u+oiJVbTcwu8hEXTu+LsP9vjlid0ZyKWw6aayMS2d30iAcz9YWZouvElR/lCeiCyI8nYi7XylRraSGevN80ADbV89DGZUFwFBJ8iWKvqpcSYNbjrJr/shfUfj1fegqPwd/2OXE9LPuS8qdquuYYwS2Tf8a2oeXnru/+IDMTanyjv/j3HSc3o+3r5DlFgN4LysvPKfMYgKJP/IhkcFsfbjAYtc+famql1zxxfQc5FL1Vai1/5TSRIvbdOfFrUWXxgtU2695UqcoUAM6vU7HuAQhddFOp9R73UduTNsZfax1wUngTaSS9Cw993PFXsQRCDNCsZsuHC5mh01M=
  provider: npm
